# iTwin.js Core Integration Validation Build
#
# This integration test job currently runs on all supported operating systems and node versions of iTwin.js.
# Runs against master on a weekly schedule, in the future this should be a required check before bumping versions.

trigger: none
pr: none

schedules:
- cron: "0 0 * * Sun"
  displayName: Weekly Sunday build
  branches:
    include:
    - master

variables:
  - group: iTwin.js non-secret config variables
  - group: iTwin.js Integration Test Users

jobs:
  - job: Integration_Tests_Full
    strategy:
      maxParallel: 1
      matrix:
        Linux_node_14_x:
          imageName: ubuntu-latest
          nodeVersion: 14.16.0
    pool:
      vmImage: $(imageName)
    steps:
      - template: templates/integration-test-steps.yaml
        parameters:
          Node_Version: $(nodeVersion)
