# This is a basic workflow that is manually triggered

name: Manual release workflow

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Name of tag for release'
        default: 'release/3.2.1'
        required: true

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout branch
      uses: actions/checkout@v2

    - name: Create release
      run: python common/scripts/create_release.py ${{ github.event.inputs.tag }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
